# Generated by Django 4.1.7 on 2023-03-01 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('game_date', models.DateTimeField()),
                ('tie_breaker', models.BooleanField(default=False)),
                ('final_score_home', models.IntegerField(default=0)),
                ('final_score_away', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='picks.game')),
                ('picker_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_team', to='picks.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_team', to='picks.team'),
        ),
    ]
